{{- if and (not .Values.secretConfig.existingSecret) .Values.secretConfig.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bluemap-web.secretName" . }}
  labels:
    {{- include "bluemap-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $path, $content := .Values.secretConfig.files }}
  {{ $path | replace "/" "__" }}: |
    {{- tpl $content $ | nindent 4 }}
  {{- end }}
{{- end }}
