{{- if and (eq .Values.storage.type "sql") (ne .Values.storage.sql.databaseType "sqlite") (not .Values.storage.sql.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bluemap-web.sqlCredentialsSecretName" . }}
  labels:
    {{- include "bluemap-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.storage.sql.credentials.usernameKey | quote }}: {{ .Values.storage.sql.credentials.username | quote }}
  {{ .Values.storage.sql.credentials.passwordKey | quote }}: {{ .Values.storage.sql.credentials.password | quote }}
{{- end }}
